### ISSUE TITLE
complete loadout should be pre-computed

### ISSUE THREAD

**Issue by Fusselwurm** [a3g/a3g-loadout#13]
When using inheritance for loadouts, several loadouts are being applied consecutively, which is both inefficient and can lead to… unintuitive results.

Example:

``` sqf
class allunits {
    primaryWeaponAttachments[] = {"acc_flashlight"};
};
class blufor {
    primaryWeapon = "something something";
};
```

Here, a blufor unit will have the "something something" weapon, but _no_ flashlight attached, because 
- adding a flashlight seems to depend on having a weapon, 
- and loadouts are being applied consecutively (allunits > blufor > class name > …)

So: Complete Loadout should be pre-computed and applied all at once.

**Comment by Cephel** [comment]
This is semantically correct, as redefining the primaryWeapon inside blufor essentially swaps it out from what the unit has normally at the time. This removes the flashlight that was applied in the prior step.

The correct way would be to assign the flashlight in the blufor class, as that's the weapon that you want to assign it to.

``` c++
class blufor {
  primaryWeapon = "something something";
  primaryWeaponAttachments[] = {"acc_flashlight"}
};
```
